### ISSUE TITLE
Are you willing to put a function that will print the version of the extension?

### ISSUE THREAD

**Issue by aloumpas** [artem-frolov/yii-sass#11]

**Comment by artem-frolov** [comment]
@aloumpas , could you please provide a use case?
If you use Composer then you can find the currently installed version there.

**Comment by aloumpas** [comment]
I don't have a specific one, i said that just in case you did not think about that. I am not using composer yet but i will soon.

**Comment by artem-frolov** [comment]
For now I don't see why such function would be needed.
Please feel free to let me know once you have a valid use case of a function like this.
Thank you!
