### ISSUE TITLE
create a lot of hex folder after compiled.

### ISSUE THREAD

**Issue by uchsarath** [artem-frolov/yii-sass#13]
I am using Opencart 1.1.x after integrate your extension then I found something wrong with out.
It generate a lof of css folder without delete previous output folder

<img width="230" alt="screen shot 2017-06-29 at 8 54 13 am" src="https://user-images.githubusercontent.com/1330852/27667991-90298726-5ca8-11e7-825e-132e450972cb.png">

How can it auto-remove the previous after each compilation?

**Comment by aloumpas** [comment]
Hello, first of all i would like to ask you, how you use this library(yii-sass) with opencart. This code uses specific commands from Yii framework. Second, this hex files does not get produced by yii-sass but from the Yii framework. This extension uses commands from the Yii assets manager. The Yii assets manager is responsible for creating this files. As i know this files can not automatically removed.

**Comment by artem-frolov** [comment]
Right, the files are published by Yii's AssetManager.
@uchsarath , If you want to change the way how the files are published then you should configure/extend your AssetManager accordingly.
