### ISSUE TITLE
how can I run Compass watch

### ISSUE THREAD

**Issue by uchsarath** [artem-frolov/yii-sass#14]
I found that the SCSS will compile after I refresh the browser, but what if I want to run
`compass watch`

what should I do?

**Comment by artem-frolov** [comment]
@uchsarath , yii-sass doesn't use original compass compiler.
If you want to use `compass watch` then you should configure your application separately.
But it doesn't make much sense to use both: yii-sass and compass, you probably want to choose one tool.
