### ISSUE TITLE
Please change             if (!file_put_contents($cssPath, $compiledCssCode, LOCK_EX)) {

### ISSUE THREAD

**Issue by tomaszbrunarski** [artem-frolov/yii-sass#15]
Please change line 359 of SassHandler from:
            if (!file_put_contents($cssPath, $compiledCssCode, LOCK_EX)) {
to:
            if (file_put_contents($cssPath, $compiledCssCode, LOCK_EX)===false) {

We have some autogenerated files that we need to be compiled in and some of them are empty, thus the file put contents returns 0 bytes written - meaning all went fine as the file compiled was empty.

**Comment by artem-frolov** [comment]
I added your fix. I also added a unit test for this case.
This change is released as 2.0.1 version.
Thank you!
