### ISSUE TITLE
Generate Absolute Path, not Relative

### ISSUE THREAD

**Issue by ChristianTheMinery** [artem-frolov/yii-sass#6]
I don't see anything in the documentation about generating an absolute path rather than a relative one, does such capability exist?

**Comment by artem-frolov** [comment]
@ChristianTheMinery , CAssetManager.publish() is used to generate paths in yii-sass.
http://www.yiiframework.com/doc/api/1.1/CAssetManager#publish-detail
So if you want to have absolute paths then you should configure assetManager in your app accordingly.
