### ISSUE TITLE
Error on SassHandler::saveParsedFilesInfoToCache

### ISSUE THREAD

**Issue by aloumpas** [artem-frolov/yii-sass#7]
* I  am trying to use the latest scssphp compiler version, which is '0.6.7' on yii 1.1.18. The error happens on the above method when trying to run 'filemtime($file)'. This happens because the returned info from the getParsedFiles() has changed a little bit.

* Return info is array( 'fileName' => 'mtime' ), so the argument is the mtime on the filemtime function

*  A solution to this is to immediately put $parsedFiles to $parsedFilesWithTime

**Comment by artem-frolov** [comment]
For reference:
scssphp behavior was changed in https://github.com/leafo/scssphp/commit/3fb23dd

**Comment by artem-frolov** [comment]
Thank you for the fix!
It's included into 2.0.0 version, please feel free to upgrade your app.

**Comment by aloumpas** [comment]
You are welcome! Thank you for the cooperation!
